[package]
name = "samples_impl"
version = "0.3.0"
edition = "2018"

[dependencies.windows]
version = "0.58"
features = [
    "Win32_Foundation",
]

[dependencies.windows-core]
version = "0.58"

[dependencies.washington-rs]
path = "../../../"
