[package]
name = "samples_impl"
version = "0.2.0"
edition = "2018"

[dependencies.windows]
version = "0.43.0"
features = [
    "implement"
]

[dependencies.washington-rs]
path = "../../../"
features = [
    "implement"
]
