[package]
name = "samples_impl"
version = "0.3.0"
edition = "2018"

[dependencies.windows]
version = "0.53"
features = [
    "implement",
    "Win32_Foundation",
]

[dependencies.washington-rs]
path = "../../../"
features = [
    "implement"
]
